package cs.classes;
// Generated Nov 18, 2014 7:49:01 PM by Hibernate Tools 3.6.0



/**
 * Answeroptions generated by hbm2java
 */
public class Answeroptions  implements java.io.Serializable {


     private Integer answerOptionsId;
     private Questions questions;
     private String answerItem;
     private Boolean isAnswer;

    public Answeroptions() {
    }

    public Answeroptions(Questions questions, String answer, Boolean isAnswer) {
       this.questions = questions;
       this.answerItem = answer;
       this.isAnswer = isAnswer;
    }
   
    public Integer getAnswerOptionsId() {
        return this.answerOptionsId;
    }
    
    public void setAnswerOptionsId(Integer answerOptionsId) {
        this.answerOptionsId = answerOptionsId;
    }
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }
    
    public String getAnswerItem() {
        return answerItem;
    }

    public void setAnswerItem(String answerItem) {
        this.answerItem = answerItem;
    }
    
    public Boolean getIsAnswer() {
        return this.isAnswer == null ? false: this.isAnswer;
    }
    
    public void setIsAnswer(Boolean isAnswer) {
        this.isAnswer = isAnswer;
    }




}


