package cs.classes;
// Generated Nov 18, 2014 7:49:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Quiz generated by hbm2java
 */
public class Quiz  implements java.io.Serializable {


     private Integer quizId;
     private String quizDescription;
     private String quizStartDatetime;
     private String quizEndDatetime;

    public String getQuizStartDatetime() {
        return quizStartDatetime;
    }

    public void setQuizStartDatetime(String quizStartDatetime) {
        this.quizStartDatetime = quizStartDatetime;
    }

    public String getQuizEndDatetime() {
        return quizEndDatetime;
    }

    public void setQuizEndDatetime(String quizEndDatetime) {
        this.quizEndDatetime = quizEndDatetime;
    }
     private Set<Questions> questionses = new HashSet<Questions>(0);
     private String CourseId;

    public String getCourseId() {
        if(CourseId == null)
        {
            return "1";
        }
        else
        {
            return CourseId;
        }
    }

    public void setCourseId(String CourseId) {
        this.CourseId = CourseId;
    }
     
    public Quiz() 
    {
        
    }

    public Quiz(String quizDescription, String quizStartDatetime, String quizendDatetime, Set<Questions> questionses) {
       this.quizDescription = quizDescription;
       this.quizStartDatetime = quizStartDatetime;
       this.quizEndDatetime = quizendDatetime;
       this.questionses = questionses;
    }
   
    public Integer getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }
    public String getQuizDescription() {
        return this.quizDescription;
    }
    
    public void setQuizDescription(String quizDescription) {
        this.quizDescription = quizDescription;
    }
   
    public Set<Questions> getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set<Questions> questionses) {
        this.questionses = questionses;
    }




}


