package cs.classes;
// Generated Nov 18, 2014 7:49:01 PM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Quiz generated by hbm2java
 */
public class Quiz  implements java.io.Serializable {


     private Integer quizId;
     private String quizDescription;
     private Date startDateTime;
     private String enteredBy;

    public String getEnteredBy() {
        return enteredBy;
    }

    public void setEnteredBy(String enteredBy) {
        this.enteredBy = enteredBy;
    }
     private ArrayList<User> userList = new ArrayList<User>();

    public ArrayList<User> getUserList() {
        return userList;
    }

    public void setUserList(ArrayList<User> userList) {
        this.userList = userList;
    }

    public Date getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    public Date getEndDateTime() {
        return endDateTime;
    }

    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }
     private Date endDateTime;

 
     private Set<Questions> questionses = new HashSet<Questions>(0);
     private String CourseId;

    public String getCourseId() {
        if(CourseId == null)
        {
            return "1";
        }
        else
        {
            return CourseId;
        }
    }

    public void setCourseId(String CourseId) {
        this.CourseId = CourseId;
    }
     
    public Quiz() 
    {
        
    }

    public Quiz(String quizDescription, Date quizStartDatetime, Date quizendDatetime, Set<Questions> questionses) {
       this.quizDescription = quizDescription;
       this.startDateTime = quizStartDatetime;
       this.endDateTime = quizendDatetime;
       this.questionses = questionses;
    }
   
    public Integer getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }
    public String getQuizDescription() {
        return this.quizDescription;
    }
    
    public void setQuizDescription(String quizDescription) {
        this.quizDescription = quizDescription;
    }
   
    public Set<Questions> getQuestionses() {
        return this.questionses;
    }
    
    public void setQuestionses(Set<Questions> questionses) {
        this.questionses = questionses;
    }




}


